### ISSUE TITLE
Referencing an older version of Cake.Core (0.22.0)

### ISSUE THREAD

**Issue by giansalex** [cake-contrib/Cake.CodeAnalysisReporting#28]
`The assembly 'Cake.CodeAnalysisReporting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.`

**Comment by pascalberger** [comment]
Closed as duplicate of #27
