### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.CodeAnalysisReporting#3]
We should add a website, created using Wyam, documenting the addin

**Comment by gep13** [comment]
@pascalberger are you planning on using Cake.Recipe on this repo?  Wyam documentation generation is already included, or are you thinking about a completely standalone repo similar to what you have with Prca.Website

**Comment by pascalberger** [comment]
@gep13 Yeah, I'm aware of the Cake.Recipe possibilities included in Wyam 😄. I think documentation should be included in this repo and published to https://github.com/cake-contrib/Cake.CodeAnalysisReporting. I don't see any advantage of having a standalone repo in this case, since it is only one single addin, not like with Cake.Prca where there are multiple addins working together (at least for the moment, but I also already have played with the idea to abstract the issue reading part 😉).

**Comment by gep13** [comment]
@pascalberger so to confirm, you are going to have a gh-pages branch in this repo, and push the documentation into there, from a set of input files in the main branch?

**Comment by pascalberger** [comment]
@gep13 Yeah that was my idea. Or should I take another approach?

**Comment by gep13** [comment]
@pascalberger nope, that sounds perfect to me, just wanted to check 😄
